version: "2"
services:
  main_service:
    build: 
      context: .
      dockerfile: /main_service/Dockerfile
    working_dir: /usr/src/app/main_service
    environment:
      - NODE_ENV=production
    expose:
      - "8082"
    command: "node server.js"
    ports:
      - "8082:8082"
    restart: always
  api_service:
    build: 
      context: .
      dockerfile: /api_service/Dockerfile
    working_dir: /usr/src/app/api_service
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    command: "npm start"
    ports:
      - "3000:3000"
    restart: always 
    volumes:
      - /usr/src/app/database