version: "3.1"
services:
  main-service:
    build:
      context: .
      dockerfile: ./main_service/Dockerfile
    working_dir: /usr/src/app/main_service
    environment:
      NODE_ENV: production
    command: "npm start"
    ports:
      - "8084:8084"
    restart: always

  matchmaker:
    build:
      context: .
      dockerfile: ./matchmaking_service/Dockerfile
    working_dir: /usr/src/app/matchmaking_service
    environment:
      NODE_ENV: production
    command: "node server.js"
    ports:
      - "8083:8083"
    restart: always

  api-service:
    build:
      context: .
      dockerfile: ./api_service/Dockerfile
    working_dir: /usr/src/app/api_service
    environment:
      NODE_ENV: production
    command: "npm start"
    ports:
      - "3002:3002"
    restart: always

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
